name: Publish
on:
  release:
    types: [created]
jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/propelauth_fastapi
      run: >-
        python -m
        pip install -r requirements.txt
        --user
    - name: Run tests
      run: python -m pytest

    - name: Build a binary wheel and a source tarball
      run: python setup.py sdist

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
